#!/usr/bin/env bash 
#set -xv 
# Detects hosts that are up and responding and centrally logs.
#. /etc/profile
#. /etc/bash.bashrc
#. /root/.bashrc
#. /root/.profile

NIC=bond0

function detect_hosts() {
	hosts=($(/usr/sbin/arp -n | grep -v incomplete | grep ${NIC} | awk '{print $1}'))
	echo ${hosts[@]}
}

function test_ssh() {
	nc -w 1 $1 22 </dev/null &>/dev/null
}

function collect_xmrig_hashes() {
	ssh -o "StrictHostKeyChecking=no" $1 journalctl -xe -u xmrig 2>/dev/null | grep [s]peed | tail -1 | awk '{ $1=""; $2=""; $3=""; $6=""; $7="";print}'
}

function execute_xmrig_hashes_on_all_hosts() {
	for i in $(detect_hosts); do
		test_ssh $i && collect_xmrig_hashes $i 
	done
}

execute_xmrig_hashes_on_all_hosts
