#!/usr/bin/env bash

source PXEfarm.sh

function usage()
{
    cat << EOF
Usage: $(basename $0) COIN
where : COIN

loki - Configures xmr-stak to mine Loki
xmr - Configures xmr-stak to mine Monero
EOF
}

function copy_config {
	cp xmrig.service /tftpboot/node_root/lib/systemd/system/xmrig.service && \
	cp build-xmrig.$1 /usr/local/bin/build-xmrig && \
	cp miner-stats /usr/local/bin/miner-stats && \
	sudo crontab -u root miner-stats.crontab
}

function update_xmrig_force {
	for i in $(arp -n | grep -v incomplete | grep bond0 | awk "{print \$1}"); do
		echo "Verifying $i is responding to SSH requests..."
		nc -w 1 $i 22 </dev/null &>/dev/null && \
		echo "SSH has been verified on $i, proceeding to restart service with new configuration." && \
		(ssh -o "StrictHostKeyChecking=no" $i "systemctl daemon-reload && systemctl stop xmrig && rm -rf /tmp/xmrig && systemctl start xmrig") &
	done
}

case $1 in
	loki|xmr)
		COIN=$1
		copy_config $COIN
		update_xmrig_force
	;;
	*)
		usage
		exit 1
	;;
esac
