#!/usr/bin/env bash

IP=10.255.255.2
+ IP=10.255.255.2
PORT=52542
+ PORT=52542
RRDTOOL="/usr/bin/rrdtool"
+ RRDTOOL=/usr/bin/rrdtool
RRD_DB="$(basename $0)"
++ basename ./blur_collect_stats.sh
+ RRD_DB=blur_collect_stats.sh

function initialize_rrd() {
        if ! [ -f $RRD_DB.rrd ] ; then
        rrdtool create $RRD_DB.rrd \
        --step 60 \
        DS:diff:GAUGE:120:0:999999999999999999 \
        DS:nthsh:GAUGE:120:0:999999999999999999 \
        DS:reward:GAUGE:120:0:999999999999999999 \
        RRA:MAX:0.5:1:1500
        fi

}
function difficulty_out() {
        curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty'
        #whitenum=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty')

}



function nethash_out() {
        #greynum=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty, .target' | xargs | awk '{print $1"/"$2}' | bc)
        curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty, .target' | xargs | awk '{print $1"/"$2}' | bc

}



reward_out() {
        height=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.height')
        sleep 1
        curl -s -X POST http://$IP:$PORT/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_coinbase_tx_sum\",\"params\":{\"height\":${height},\"count\":3}}" -H 'Content-Type: application/json' | jq '.result.emission_amount' | awk '{print $0/1000000000000}'

}

function graph_output() {
        ## Graph for last 24 hours
$RRDTOOL graph $RRD_DB.png \
-w 785 -h 120 -a PNG \
--slope-mode \
--start -86400 --end now \
--font DEFAULT:7: \
--title "Blur Stats gateway" \
--watermark "$(date)" \
--vertical-label "count" \
--right-axis-label "date" \
--lower-limit 0 \
--right-axis 1:0 \
--x-grid MINUTE:10:HOUR:1:MINUTE:120:0:%R \
--alt-y-grid --rigid \
DEF:Difficulty=$RRD_DB.rrd:diff:MAX \
DEF:NetHash=$RRD_DB.rrd:nthsh:MAX \
DEF:Reward=$RRD_DB.rrd:reward:MAX \
LINE1:Difficulty#0000FF:"difficulty" \
LINE2:NetHash#00FFFF:"nethash" \
LINE3:Reward#FFFFFF:"reward" \
GPRINT:Difficulty:LAST:"Cur\: %5.2lf" \
GPRINT:Difficulty:AVERAGE:"Avg\: %5.2lf" \
GPRINT:Difficulty:MAX:"Max\: %5.2lf" \
GPRINT:Difficulty:MIN:"Min\: %5.2lf\t\t\t"
}

initialize_rrd
+ initialize_rrd
+ '[' -f blur_collect_stats.sh.rrd ']'
DATA=$(echo $(difficulty_out):$(nethash_out):$(reward_out))
+++ difficulty_out
+++ jq .difficulty
+++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
+++ nethash_out
+++ xargs
+++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
+++ awk '{print $1"/"$2}'
+++ bc
+++ jq '.difficulty, .target'
+++ reward_out
++++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
++++ jq .height
+++ height=746324
+++ sleep 1
+++ curl -s -X POST http://10.255.255.2:52542/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_coinbase_tx_sum","params":{"height":746324,"count":3}}' -H 'Content-Type: application/json'
+++ awk '{print $0/1000000000000}'
+++ jq .result.emission_amount
++ echo 55504161:925069:0
+ DATA=55504161:925069:0
$RRDTOOL update $RRD_DB.rrd --template diff:nthsh:reward N:$DATA
+ /usr/bin/rrdtool update blur_collect_stats.sh.rrd --template diff:nthsh:reward N:55504161:925069:0
graph_output
+ graph_output
++ date
+ /usr/bin/rrdtool graph blur_collect_stats.sh.png -w 785 -h 120 -a PNG --slope-mode --start -86400 --end now --font DEFAULT:7: --title 'Blur Stats gateway' --watermark 'Sat Dec  7 23:32:22 CST 2019' --vertical-label count --right-axis-label date --lower-limit 0 --right-axis 1:0 --x-grid MINUTE:10:HOUR:1:MINUTE:120:0:%R --alt-y-grid --rigid DEF:Difficulty=blur_collect_stats.sh.rrd:diff:MAX DEF:NetHash=blur_collect_stats.sh.rrd:nthsh:MAX DEF:Reward=blur_collect_stats.sh.rrd:reward:MAX LINE1:Difficulty#0000FF:difficulty LINE2:NetHash#00FFFF:nethash LINE3:Reward#FFFFFF:reward 'GPRINT:Difficulty:LAST:Cur\: %5.2lf' 'GPRINT:Difficulty:AVERAGE:Avg\: %5.2lf' 'GPRINT:Difficulty:MAX:Max\: %5.2lf' 'GPRINT:Difficulty:MIN:Min\: %5.2lf\t\t\t'
930x199

paul.pasika@amagi-firewall:~$ sudo cp blur_collect_stats.sh.png /var/lib/xymon/www/
paul.pasika@amagi-firewall:~$ sudo rm /var/lib/xymon/www/blur_collect_stats.sh.png
paul.pasika@amagi-firewall:~$ bash -xv ./blur_collect_stats.sh
#!/usr/bin/env bash

IP=10.255.255.2
PORT=52542
+ PORT=52542
RRDTOOL="/usr/bin/rrdtool"
+ RRDTOOL=/usr/bin/rrdtool
RRD_DB="$(basename $0)"
++ basename ./blur_collect_stats.sh
+ RRD_DB=blur_collect_stats.sh

function initialize_rrd() {
        if ! [ -f $RRD_DB.rrd ] ; then
        rrdtool create $RRD_DB.rrd \
        --step 60 \
        DS:diff:GAUGE:120:0:999999999999999999 \
        DS:nthsh:GAUGE:120:0:999999999999999999 \
        DS:reward:GAUGE:120:0:999999999999999999 \
        RRA:MAX:0.5:1:1500
        fi

}
function difficulty_out() {
        curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty'
        #whitenum=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty')

}



function nethash_out() {
        #greynum=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty, .target' | xargs | awk '{print $1"/"$2}' | bc)
        curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.difficulty, .target' | xargs | awk '{print $1"/"$2}' | bc

}



reward_out() {
        height=$(curl -s -X POST http://$IP:$PORT/getinfo -H 'Content-Type: application/json' | jq '.height')
        sleep 1
        curl -s -X POST http://$IP:$PORT/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_coinbase_tx_sum\",\"params\":{\"height\":${height},\"count\":3}}" -H 'Content-Type: application/json' | jq '.result.emission_amount' | awk '{print $0/1000000000000}'

}

function graph_output() {
        ## Graph for last 24 hours
$RRDTOOL graph $RRD_DB.png \
-w 785 -h 120 -a PNG \
--slope-mode \
--start -86400 --end now \
--font DEFAULT:7: \
--title "Blur Stats gateway" \
--watermark "$(date)" \
--vertical-label "count" \
--right-axis-label "date" \
--lower-limit 0 \
--right-axis 1:0 \
--x-grid MINUTE:10:HOUR:1:MINUTE:120:0:%R \
--alt-y-grid --rigid \
DEF:Difficulty=$RRD_DB.rrd:diff:MAX \
DEF:NetHash=$RRD_DB.rrd:nthsh:MAX \
DEF:Reward=$RRD_DB.rrd:reward:MAX \
LINE1:Difficulty#0000FF:"difficulty" \
LINE2:NetHash#00FFFF:"nethash" \
LINE3:Reward#FFFFFF:"reward" \
GPRINT:Difficulty:LAST:"Cur\: %5.2lf" \
GPRINT:Difficulty:AVERAGE:"Avg\: %5.2lf" \
GPRINT:Difficulty:MAX:"Max\: %5.2lf" \
GPRINT:Difficulty:MIN:"Min\: %5.2lf\t\t\t"
}

initialize_rrd
+ initialize_rrd
+ '[' -f blur_collect_stats.sh.rrd ']'
DATA=$(echo $(difficulty_out):$(nethash_out):$(reward_out))
+++ difficulty_out
+++ jq .difficulty
+++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
+++ nethash_out
+++ awk '{print $1"/"$2}'
+++ bc
+++ xargs
+++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
+++ jq '.difficulty, .target'
+++ reward_out
++++ curl -s -X POST http://10.255.255.2:52542/getinfo -H 'Content-Type: application/json'
++++ jq .height
+++ height=746324
+++ sleep 1
+++ jq .result.emission_amount
+++ curl -s -X POST http://10.255.255.2:52542/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_coinbase_tx_sum","params":{"height":746324,"count":3}}' -H 'Content-Type: application/json'
+++ awk '{print $0/1000000000000}'
++ echo 55504161:925069:0
+ DATA=55504161:925069:0
$RRDTOOL update $RRD_DB.rrd --template diff:nthsh:reward N:$DATA
+ /usr/bin/rrdtool update blur_collect_stats.sh.rrd --template diff:nthsh:reward N:55504161:925069:0
graph_output
