#!/usr/bin/env bash

set -xv 
source /etc/bash.bashrc
source /etc/profile


# Abort of running on an A4-3400 CPU, xmrig currently wont run on these:
lscpu | grep -w A4-3300 && exit 0

	#VERSION=feature-hwloc
	POOL="10.255.255.2:52542"
	WALLET="bL3j7Pbbc49ZM3Rmx9XabReVRLTruCMZjNFa6wd59tZS9TAGwc2MsstFvtamTq6DSzKN12CRzaQ4ecQWHznJeycD3BFi6F3ap"
	PASS="pxe"
	COIN="monero"
	cd /tmp
	rm -rf blur-miner 2>/dev/null
	git clone https://github.com/fart-master/blur-miner.git
	cd blur-miner
	mkdir bin
	cd bin
	# AOCC Changes
	source /opt/AMD/aocc-compiler-2.1.0/setenv_AOCC.sh
	export CC=/opt/AMD/aocc-compiler-2.1.0/bin/clang
	export CXX=/opt/AMD/aocc-compiler-2.1.0/bin/clang++
	cmake -WITH_OPENCL=OFF -DCMAKE_C_FLAGS="-O3 -march=native -funroll-loops -fomit-frame-pointer" ..
	#cmake -WITH_OPENCL=OFF ..
	make -j12
	mkdir -p cuda
	cd cuda
	unset CC
	unset CXX
	cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-6 ../../xmrig-cuda
	make -j12
	cp ./libxmrig-cuda.so ../libxmrig-cuda.so
	cd -


	#!/bin/bash
	dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

	rm -rf ${dir}/build

	sysctl -w vm.nr_hugepages=1250
	cat << EOF > config.json
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": true,
    "colors": true,
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": true,
        "priority": null,
        "memory-pool": false,
        "cn/blur": {
            "threads": null
        }
    },
    "opencl": {
        "enabled": false
    },
    "cuda": {
        "enabled": true,
	"loader": "$(pwd)/libxmrig-cuda.so",
        "nvml": true,
        "cn/blur": [{
            "index": 0,
            "threads": 24,
            "blocks": 20,
            "bfactor": 0,
            "bsleep": 0,
            "affinity": -1
        }]
    },
    "log-file": null,
    "pools": [{
        "url": "$POOL",
        "user": "$WALLET",
        "enabled": true,
        "tls": false,
        "tls-fingerprint": null,
        "daemon": true,
        "daemon-poll-interval": 25
    }],
    "print-time": 5,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": true,
    "user-agent": null,
    "watch": true
}

EOF
	#./xmrig | logger -t xmrig

modprobe msr
#
if cat /proc/cpuinfo | grep "AMD Ryzen" > /dev/null;
then
echo "Detected Ryzen"
wrmsr -a 0xc0011022 0x510000
wrmsr -a 0xc001102b 0x1808cc16
wrmsr -a 0xc0011020 0
wrmsr -a 0xc0011021 0x40
echo "MSR register values for Ryzen applied"
elif cat /proc/cpuinfo | grep "Intel" > /dev/null;
then
echo "Detected Intel - Disable tuning for now... ppasika"
echo wrmsr -a 0x1a4 0xf
echo "MSR register values for Intel applied"
else
echo "No supported CPU detected"
fi
